# Generated by Django 4.2.16 on 2025-11-01 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(help_text='Ej: Frontend, Backend, Diseño', max_length=50)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='intermedio', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(help_text='Ej: Desarrollador Full Stack, Diseñador UX/UI', max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('biografia', models.TextField(help_text='Tu historia profesional')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('github', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('objetivos', models.TextField(blank=True, help_text='Tus objetivos profesionales')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('profesional', 'Profesional'), ('personal', 'Personal'), ('academico', 'Académico')], default='profesional', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trabajos/')),
                ('url_proyecto', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('url_repositorio', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('tecnologias', models.CharField(help_text='Tecnologías usadas, separadas por comas', max_length=500)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en la página de inicio')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-destacado', 'orden', '-fecha_realizacion'],
            },
        ),
    ]
