# Generated by Django 4.2.16 on 2025-11-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trabajo', 'Experiencia Laboral'), ('educacion', 'Educación'), ('certificacion', 'Certificación')], default='trabajo', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('empresa_institucion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de las responsabilidades o logros')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío si es actual', null=True)),
                ('es_actual', models.BooleanField(default=False, help_text='Marcar si es la posición/estudio actual')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (mayor = más reciente)')),
            ],
            options={
                'verbose_name_plural': 'Currículum',
                'ordering': ['-orden', '-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='habilidad',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Logo/icono de la tecnología (recomendado: 64x64px)', null=True, upload_to='tecnologias/'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='mostrar_en_circulo',
            field=models.BooleanField(default=False, help_text='Mostrar en la sección de tecnologías con animación circular'),
        ),
    ]
